<?php
/**
 * ShippingOption
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\account
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Account API
 *
 * The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br/><br/>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.
 *
 * The version of the OpenAPI document: v1.8.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\account\Model;

use \ArrayAccess;
use \macropage\SDKs\ebay\rest\account\ObjectSerializer;

/**
 * ShippingOption Class Doc Comment
 *
 * @category Class
 * @description This type is used by the &lt;b&gt;shippingOptions&lt;/b&gt; array, which is used to provide detailed information on the domestic and international shipping options available for the policy. A separate &lt;b&gt;ShippingOption&lt;/b&gt; object covers domestic shipping service options and international shipping service options (if the seller ships to international locations).
 * @package  macropage\SDKs\ebay\rest\account
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShippingOption implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShippingOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'costType' => 'string',
        'insuranceFee' => '\macropage\SDKs\ebay\rest\account\Model\Amount',
        'insuranceOffered' => 'bool',
        'optionType' => 'string',
        'packageHandlingCost' => '\macropage\SDKs\ebay\rest\account\Model\Amount',
        'rateTableId' => 'string',
        'shippingServices' => '\macropage\SDKs\ebay\rest\account\Model\ShippingService[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'costType' => null,
        'insuranceFee' => null,
        'insuranceOffered' => null,
        'optionType' => null,
        'packageHandlingCost' => null,
        'rateTableId' => null,
        'shippingServices' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'costType' => false,
		'insuranceFee' => false,
		'insuranceOffered' => false,
		'optionType' => false,
		'packageHandlingCost' => false,
		'rateTableId' => false,
		'shippingServices' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'costType' => 'costType',
        'insuranceFee' => 'insuranceFee',
        'insuranceOffered' => 'insuranceOffered',
        'optionType' => 'optionType',
        'packageHandlingCost' => 'packageHandlingCost',
        'rateTableId' => 'rateTableId',
        'shippingServices' => 'shippingServices'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'costType' => 'setCostType',
        'insuranceFee' => 'setInsuranceFee',
        'insuranceOffered' => 'setInsuranceOffered',
        'optionType' => 'setOptionType',
        'packageHandlingCost' => 'setPackageHandlingCost',
        'rateTableId' => 'setRateTableId',
        'shippingServices' => 'setShippingServices'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'costType' => 'getCostType',
        'insuranceFee' => 'getInsuranceFee',
        'insuranceOffered' => 'getInsuranceOffered',
        'optionType' => 'getOptionType',
        'packageHandlingCost' => 'getPackageHandlingCost',
        'rateTableId' => 'getRateTableId',
        'shippingServices' => 'getShippingServices'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('costType', $data ?? [], null);
        $this->setIfExists('insuranceFee', $data ?? [], null);
        $this->setIfExists('insuranceOffered', $data ?? [], null);
        $this->setIfExists('optionType', $data ?? [], null);
        $this->setIfExists('packageHandlingCost', $data ?? [], null);
        $this->setIfExists('rateTableId', $data ?? [], null);
        $this->setIfExists('shippingServices', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets costType
     *
     * @return string|null
     */
    public function getCostType()
    {
        return $this->container['costType'];
    }

    /**
     * Sets costType
     *
     * @param string|null $costType This field defines whether the shipping cost model is <code>FLAT_RATE</code> (the same rate for all buyers, or buyers within a region if shipping rate tables are used) or <code>CALCULATED</code> (the shipping rate varies by the ship-to location and size and weight of the package). <br/><br/>This field is conditionally required if any shipping service options are specified (domestic and/or international). For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ShippingCostTypeEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setCostType($costType)
    {

        if (is_null($costType)) {
            throw new \InvalidArgumentException('non-nullable costType cannot be null');
        }

        $this->container['costType'] = $costType;

        return $this;
    }

    /**
     * Gets insuranceFee
     *
     * @return \macropage\SDKs\ebay\rest\account\Model\Amount|null
     */
    public function getInsuranceFee()
    {
        return $this->container['insuranceFee'];
    }

    /**
     * Sets insuranceFee
     *
     * @param \macropage\SDKs\ebay\rest\account\Model\Amount|null $insuranceFee insuranceFee
     *
     * @return self
     */
    public function setInsuranceFee($insuranceFee)
    {

        if (is_null($insuranceFee)) {
            throw new \InvalidArgumentException('non-nullable insuranceFee cannot be null');
        }

        $this->container['insuranceFee'] = $insuranceFee;

        return $this;
    }

    /**
     * Gets insuranceOffered
     *
     * @return bool|null
     */
    public function getInsuranceOffered()
    {
        return $this->container['insuranceOffered'];
    }

    /**
     * Sets insuranceOffered
     *
     * @param bool|null $insuranceOffered This field has been deprecated. <br/><br/>Shipping insurance is offered only via a shipping carrier's shipping services and is no longer available via eBay shipping policies.
     *
     * @return self
     */
    public function setInsuranceOffered($insuranceOffered)
    {

        if (is_null($insuranceOffered)) {
            throw new \InvalidArgumentException('non-nullable insuranceOffered cannot be null');
        }

        $this->container['insuranceOffered'] = $insuranceOffered;

        return $this;
    }

    /**
     * Gets optionType
     *
     * @return string|null
     */
    public function getOptionType()
    {
        return $this->container['optionType'];
    }

    /**
     * Sets optionType
     *
     * @param string|null $optionType This field is used to indicate if the corresponding shipping service options (under <b>shippingServices</b> array) are domestic or international shipping service options. This field is conditionally required if any shipping service options are specified (domestic and/or international). For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ShippingOptionTypeEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setOptionType($optionType)
    {

        if (is_null($optionType)) {
            throw new \InvalidArgumentException('non-nullable optionType cannot be null');
        }

        $this->container['optionType'] = $optionType;

        return $this;
    }

    /**
     * Gets packageHandlingCost
     *
     * @return \macropage\SDKs\ebay\rest\account\Model\Amount|null
     */
    public function getPackageHandlingCost()
    {
        return $this->container['packageHandlingCost'];
    }

    /**
     * Sets packageHandlingCost
     *
     * @param \macropage\SDKs\ebay\rest\account\Model\Amount|null $packageHandlingCost packageHandlingCost
     *
     * @return self
     */
    public function setPackageHandlingCost($packageHandlingCost)
    {

        if (is_null($packageHandlingCost)) {
            throw new \InvalidArgumentException('non-nullable packageHandlingCost cannot be null');
        }

        $this->container['packageHandlingCost'] = $packageHandlingCost;

        return $this;
    }

    /**
     * Gets rateTableId
     *
     * @return string|null
     */
    public function getRateTableId()
    {
        return $this->container['rateTableId'];
    }

    /**
     * Sets rateTableId
     *
     * @param string|null $rateTableId This field is used if the seller wants to associate a domestic or international shipping rate table to the fulfillment business policy. The <a href=\"/api-docs/sell/account/resources/rate_table/methods/getRateTables\">getRateTables</a> method can be used to retrieve shipping rate table IDs.<br/><br/>With domestic and international shipping rate tables, the seller can set different shipping costs based on shipping regions and shipping speed/level of service (one-day, expedited, standard, economy). There are also options to additional per-weight and handling charges.<br/><br/>Sellers need to be careful that shipping rate tables match the corresponding shipping service options. In other words, a domestic shipping rate table must not be specified in the same container where international shipping service options are being specified, and vice versa, and the shipping speed/level of service of the provided shipping service options should match the shipping speed/level of service options that are defined in the shipping rate tables. For example, if the corresponding shipping rate table defines costs for one-day shipping services, there should be at least one one-day shipping service option specified under the <b>shippingServices</b> array.<br/><br/>This field is returned if set.
     *
     * @return self
     */
    public function setRateTableId($rateTableId)
    {

        if (is_null($rateTableId)) {
            throw new \InvalidArgumentException('non-nullable rateTableId cannot be null');
        }

        $this->container['rateTableId'] = $rateTableId;

        return $this;
    }

    /**
     * Gets shippingServices
     *
     * @return \macropage\SDKs\ebay\rest\account\Model\ShippingService[]|null
     */
    public function getShippingServices()
    {
        return $this->container['shippingServices'];
    }

    /**
     * Sets shippingServices
     *
     * @param \macropage\SDKs\ebay\rest\account\Model\ShippingService[]|null $shippingServices This array consists of the domestic or international shipping services options that are defined for the policy. The shipping service options defined under this array should match what is set in the corresponding <b>shippingOptions.optionType</b> field (which controls whether domestic or international shipping service options are being defined). If a shipping rate table is being used, the specified shipping service options should also match the shipping rate table settings (domestic or international, shipping speed/level of service, etc.) <br/><br/>Sellers can specify up to four domestic shipping services and up to five international shipping service options by using separate <b>shippingService</b> containers for each. If the seller is using the Global Shipping Program as an international option, only a total of four international shipping service options (including GSP) can be offered. <br/><br/> See <a href=\"/api-docs/sell/static/seller-accounts/ht_shipping-setting-shipping-carrier-and-service-values.html\" target=\"_blank\">How to set up shipping carrier and shipping service values</a>. <br /><br />To use the eBay standard envelope service (eSE), see <a href=\"/api-docs/sell/static/seller-accounts/using-the-ebay-standard-envelope-service.html\" target=\"_blank\">Using eBay standard envelope (eSE) service</a>.<br /><br />This array is conditionally required if the seller is offering one or more domestic and/or international shipping service options.
     *
     * @return self
     */
    public function setShippingServices($shippingServices)
    {

        if (is_null($shippingServices)) {
            throw new \InvalidArgumentException('non-nullable shippingServices cannot be null');
        }

        $this->container['shippingServices'] = $shippingServices;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


