<?php
/**
 * ShippingOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Account API
 *
 * The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (the Fulfillment Policy, Payment Policy, and Return Policy), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the restrictions and availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#acct-restrictions\">API restrictions</a>.
 *
 * OpenAPI spec version: v1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ShippingOptionTest Class Doc Comment
 *
 * @category    Class
 * @description This complex type defines a seller&#39;s shipping configuration for either a DOMESTIC or INTERNATIONAL shipping option. Shipping options configure the high-level settings for shipments, such as flat-rate or calculated shipping, and any rate tables the seller wants to associate with the policy. Each shippingOption element has a shippingServices container that defines the list of shipping carriers and services that are available for the parent shipping option (that is, for either DOMESTIC or INTERNATIONAL shipping). If a seller offers an international shipping option, they must also offer a domestic shipping option. Note that costType (FLAT_RATE or CALCULATED) is set in shippingOptions and that all associated shipping services must be able to support this cost type.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingOptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingOption"
     */
    public function testShippingOption()
    {
    }

    /**
     * Test attribute "cost_type"
     */
    public function testPropertyCostType()
    {
    }

    /**
     * Test attribute "insurance_fee"
     */
    public function testPropertyInsuranceFee()
    {
    }

    /**
     * Test attribute "insurance_offered"
     */
    public function testPropertyInsuranceOffered()
    {
    }

    /**
     * Test attribute "option_type"
     */
    public function testPropertyOptionType()
    {
    }

    /**
     * Test attribute "package_handling_cost"
     */
    public function testPropertyPackageHandlingCost()
    {
    }

    /**
     * Test attribute "rate_table_id"
     */
    public function testPropertyRateTableId()
    {
    }

    /**
     * Test attribute "shipping_services"
     */
    public function testPropertyShippingServices()
    {
    }
}
